### ISSUE TITLE
关于你的cpython pr

### ISSUE THREAD

**Issue by Wulian233** [rruuaanng/design_parttern_edu#1]
也没找到你的邮箱，那里又不能直接打中文，这里和你说一下吧🤦🏻‍♂️

https://github.com/python/cpython/pull/124051

这个pr有2个工作流运行失败，一个是文档的格式化问题，一个是2个测试失败

我一直和你说的是文档测试失败，就是mod meth的方法引用，我review了2次你都没改到点上😥文档格式不是多个空格少个空格的事。我review suggestion后你可以直接点commit提交。这个就是在模块里找方法，你相当于现在在模块里又找模块又找方法

至于python 里的格式，不要多加空行，这点已经改了

第二个是测试失败，因为你改了代码，所以之前的运行结果和现在的不一样。测试就是带着结果看问题的判卷子过程，问题改了，答案就不匹配了。我发了具体的失败类，可以看一看。

希望你能看到。

另外，没core dev review你的代码很正常，不要随便就close了……

这个pr的代码我觉得就悬，估计要找一找人

**Comment by rruuaanng** [comment]
> 也没找到你的邮箱，那里又不能直接打中文，这里和你说一下吧🤦🏻‍♂️
> 
> [python/cpython#124051](https://github.com/python/cpython/pull/124051)
> 
> 这个pr有2个工作流运行失败，一个是文档的格式化问题，一个是2个测试失败
> 
> 我一直和你说的是文档测试失败，就是mod meth的方法引用，我review了2次你都没改到点上😥文档格式不是多个空格少个空格的事。我review suggestion后你可以直接点commit提交。这个就是在模块里找方法，你相当于现在在模块里又找模块又找方法
> 
> 至于python 里的格式，不要多加空行，这点已经改了
> 
> 第二个是测试失败，因为你改了代码，所以之前的运行结果和现在的不一样。测试就是带着结果看问题的判卷子过程，问题改了，答案就不匹配了。我发了具体的失败类，可以看一看。
> 
> 希望你能看到。
> 
> 另外，没core dev review你的代码很正常，不要随便就close了……
> 
> 这个pr的代码我觉得就悬，估计要找一找人

我知道这个PR大概率是废了，这个密码泄露触发的条件很困难，因为要客户端远程读取服务端的标准输出。但是不存在不把异常给try掉

**Comment by rruuaanng** [comment]
> 也没找到你的邮箱，那里又不能直接打中文，这里和你说一下吧🤦🏻‍♂️
> 
> [python/cpython#124051](https://github.com/python/cpython/pull/124051)
> 
> 这个pr有2个工作流运行失败，一个是文档的格式化问题，一个是2个测试失败
> 
> 我一直和你说的是文档测试失败，就是mod meth的方法引用，我review了2次你都没改到点上😥文档格式不是多个空格少个空格的事。我review suggestion后你可以直接点commit提交。这个就是在模块里找方法，你相当于现在在模块里又找模块又找方法
> 
> 至于python 里的格式，不要多加空行，这点已经改了
> 
> 第二个是测试失败，因为你改了代码，所以之前的运行结果和现在的不一样。测试就是带着结果看问题的判卷子过程，问题改了，答案就不匹配了。我发了具体的失败类，可以看一看。
> 
> 希望你能看到。
> 
> 另外，没core dev review你的代码很正常，不要随便就close了……
> 
> 这个pr的代码我觉得就悬，估计要找一找人

主要是我之前提交的几个NEWS都是这样写的，我不明白为什么这个不行

**Comment by rruuaanng** [comment]
@Wulian233

**Comment by rruuaanng** [comment]
我关闭掉算了，这个如果要改测试要改一堆
